FROM openjdk:11-jre

COPY target/kafka-producer-1.0-SNAPSHOT-jar-with-dependencies.jar /

CMD java -jar kafka-producer-1.0-SNAPSHOT-jar-with-dependencies.jar

ENTRYPOINT java -jar kafka-producer-1.0-SNAPSHOT-jar-with-dependencies.jar